#ifdef CH_LANG_CC
/*
 *      _______              __
 *     / ___/ /  ___  __ _  / /  ___
 *    / /__/ _ \/ _ \/  V \/ _ \/ _ \
 *    \___/_//_/\___/_/_/_/_.__/\___/
 *    Please refer to Copyright.txt, in Chombo's root directory.
 */
#endif

#ifndef CHOMBO_8D49E3B4_9C4C_4AC3_A365_8CDB4A19C138
#define CHOMBO_8D49E3B4_9C4C_4AC3_A365_8CDB4A19C138

#include <cstddef>

#include "NamespaceHeader.H"

enum ARK4Sizes : std::size_t
{
  s_nStages = 6,
  s_nDenseCoefs = 3
};

#include "NamespaceFooter.H"
#endif 
