/*
 *      _______              __ 
 *     / ___/ /  ___  __ _  / /  ___
 *    / /__/ _ \/ _ \/  V \/ _ \/ _ \
 *    \___/_//_/\___/_/_/_/_.__/\___/
 *    Please refer to Copyright.txt, in Chombo's root directory.
 */

////////////////////////////////////////////////////////////////////////////////
//  Copyright (c) 2014-2016 Bryce Adelstein-Lelbach
//
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
////////////////////////////////////////////////////////////////////////////////

#if !defined(CHOMBO_56A1AE8E_D5C3_4A4A_9A30_907B1F3CDB9C)
#define CHOMBO_56A1AE8E_D5C3_4A4A_9A30_907B1F3CDB9C

#define CH_PP_STRINGIZE_(expr) #expr
#define CH_PP_STRINGIZE(expr) CH_PP_STRINGIZE_(expr)

#endif // CHOMBO_56A1AE8E_D5C3_4A4A_9A30_907B1F3CDB9C

